### ISSUE TITLE
你好，请教一个问题，天眼查接口请求头的Authorization这个字段过期时间是多久呢

### ISSUE THREAD

**Issue by yu1002139909** [cyr2270556/spider_project#2]
如图

**Comment by cyr2270556** [comment]
func文件里面的吗，那个不是我写的早都没维护了，而且这个git上面的很久没上传了 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月16日(星期五) 上午10:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cyr2270556/spider_project] 你好，请教一个问题，天眼查接口请求头的Authorization这个字段过期时间是多久呢 (#2)

**Comment by yu1002139909** [comment]
对的 那您这边研究过那个token没呢

**Comment by cyr2270556** [comment]
没有，接口都是走官方的，爬虫是走不了接口的

**Comment by yu1002139909** [comment]
好的谢谢
